language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 mypy wget
# command to run tests
script:
  - ./build.sh
env:
  - TRAIN_FILENAME="en_gum-ud-train.conllu" DEV_FILENAME="en_gum-ud-dev.conllu" TEST_FILENAME="en_gum-ud-test.conllu" TEXT_FILENAME="unlabeled.txt"
