language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 mypy
# command to run tests
script:
  - flake8 *.py
  - mypy --ignore-missing-imports *.py
